[versions]
agp = "8.13.2"

kotlin = "2.3.10"
core-ktx = "1.17.0"
activity-compose = "1.12.4"
compose-multiplatform = "1.10.1"
compose-material3 = "1.9.0"

vanniktech-maven-publish = "0.36.0"

[libraries]
# Multiplatform:
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }

# Android:
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[bundles]
androidx-compose = ["androidx-core-ktx", "androidx-activity-compose"]
androidx-compose-debug = ["androidx-ui-graphics", "androidx-ui-tooling", "androidx-ui-tooling-preview"]
compose = ["compose-runtime", "compose-foundation", "compose-material3", "compose-ui"]

[plugins]
# Multiplatform:
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
 vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }

# Android
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Desktop
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }


